config/routes.rb
Rails.application.routes.draw do
  resources :materials

  get 'pages/admin'

  resources :prices

  resources :banks

  resources :movements do
    collection do
      get 'accountant'
    end
  end

  resources :accounts

  resources :result_centers

  get 'payment_documents/generate'
  get 'payment_documents/new'
  post 'payment_documents/create'
  post 'payment_documents/insert'
  get 'payment_documents/payment'
  get 'payment_documents/edit'
  post 'payment_documents/update'
  post 'payment_documents/confirm'

  resources :subscriptions

  resources :salesmen

  resources :participants

  resources :companies

  resources :course_classes do
    member do
      get 'subscriptions'
      get 'prices'
    end
  end

  resources :trainers

  resources :courses

  devise_for :users, :controllers => { :registrations => "registrations", :invitations => "invitations" }
  resources :users
  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/movement.rb
class Movement < ActiveRecord::Base
  belongs_to :course_class
  belongs_to :account
  belongs_to :result_center
  belongs_to :bank
  belongs_to :to_bank, class_name: "Bank", foreign_key: "to_bank_id"
  has_one :payment_document
  has_one :transfer_movement, class_name: "Movement", foreign_key: "transfer_movement_id"
  has_many :materials
  has_attached_file :document_image
  has_attached_file :receipt_image

  scope :recent, -> { where("due_date >= ?", Date.today - 3.days) }
  scope :materialsa, -> { joins(:bank).where("material = 1").order("due_date DESC") }

  validates_presence_of :due_date, :description, :value, :account, :result_center, :bank
  validates_numericality_of :value, message: "O valor precisa ser um número"
  validates_attachment_content_type :document_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]
  validates_attachment_content_type :receipt_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]

  before_create :create_transfer_movement
  
  def to_s
    "#{self.due_date.strftime('%d/%m/%Y')} - #{self.description} - #{self.value}"
  end

  def create_transfer_movement
  	if self.transfer then
  		self.transfer_movement = self.dup
  		self.transfer_movement.bank_id = self.transfer_movement.to_bank_id
  		self.transfer_movement.to_bank_id = nil
  		self.transfer_movement.credit = !self.transfer_movement.credit
  	end
    true
  end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html

  def index
    @movements = if params.count > 2
      Movement.all.includes(:account, :bank, :result_center, :course_class).order(:due_date)
    else
      Movement.recent.includes(:account, :bank, :result_center, :course_class).order(:due_date)
    end
    @movements = @movements.where("due_date >= ?", params[:sd]) if params[:sd] && !params[:sd].empty?
    @movements = @movements.where("due_date <= ?", params[:ed]) if params[:ed] && !params[:ed].empty?
    @movements = @movements.where("description LIKE ?", "%#{params[:d]}%") if params[:d] && !params[:d].empty?
    @movements = @movements.where("bank_id = ?", params[:b]) if params[:b] && !params[:b].empty?
    if params[:v] && !params[:v].empty? then
      v = params[:v].to_i
      @movements = @movements.where("value >= ? and value <= ?", v-1, v+1) 
    end
    @banks = Bank.all
    respond_with(@movements)
  end

  def accountant
    @movements = []
    @movements = Movement.where(accountable: true).where("due_date >= ? and due_date <= ?", params[:sd], params[:ed]) if params[:sd] && !params[:sd].empty? && params[:ed] && !params[:ed].empty?
    respond_with(@movements)
  end

  def show
    respond_with(@movement)
  end

  def new
    @movement = Movement.new
    respond_with(@movement)
  end

  def edit
  end

  def create
    @movement = Movement.new(movement_params)
    @movement.save
    respond_with(@movement)
  end

  def update
    @movement.update(movement_params)
    respond_with(@movement)
  end

  def destroy
    @movement.destroy
    respond_with(@movement)
  end

  private
    def set_movement
      @movement = Movement.find(params[:id])
    end

    def movement_params
      params.require(:movement).permit(:due_date, :description, :value, :course_class_id, :account_id, :result_center_id, :bank_id, :transfer, :to_bank_id, :credit, :accountable, :document_image, :receipt_image)
    end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

class MovementTransferenceValidator < ActiveModel::Validator
  def validate(record)
    if record.transfer && record.to_bank.empty?
      record.errors[:base] = "Toda transferência deve indicar para qual banco"
    end
  end
end

app/views/movements/_form.html.erb
<%= simple_form_for(@movement) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :due_date %>
    <%= f.input :description %>
    <%= f.input :value %>
    <%= f.input :credit, as: :radio_buttons, label: false, collection: [["Crédito/Recebimento", "1"], ["Débito/Pagamento", "0"]] %>
    <%= f.association :course_class, collection: CourseClass.includes(:course).order("courses.code, city, identifier desc") %>
    <%= f.association :account, collection: Account.ordered_list %>
    <%= f.association :result_center %>
    <%= f.association :bank %>
    <%= f.input :transfer, inline_label: "Transferência", label: false %>
    <%= f.association :to_bank %>
    <%= f.input :accountable, inline_label: "Enviar para contabilidade", label: false %>
    <%= f.input :document_image, as: :file %>
    <%= f.input :receipt_image, as: :file %>
    </div></div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movements/accountant.html.erb
<h1>Movimentos financeiros para Contabilidade</h1>
 
<%= form_tag(accountant_movements_path, method: :get) do %>
Começando em <%= date_field_tag "sd", params[:sd] %> até <%= date_field_tag "ed", params[:ed] %> <%= submit_tag "Pesquisar" %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Data</th>
      <th>Description</th>
      <th>Valor</th>
      <th>CC/Caixa</th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
        <td><%= l movement.due_date %></td>
        <td><%= movement.description %></td>
        <td style="text-align: right;"><%= number_to_currency movement.value, unit: "" %>&nbsp;<%= movement.credit ? "C" : "D" %></td>
        <td><%= movement.bank %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movements/edit.html.erb
<h1>Editing movement</h1>

<%= render 'form' %>

<%= link_to t("commands.show"), @movement %> |
<%= link_to t("commands.back"), movements_path %>

app/views/movements/index.html.erb
<div class="form-inputs panel panel-primary" style="margin-top:10px;">
    <div class="panel-heading"><a class="search-link" href="javascript:$('#search-params').toggle()">Pesquisar Movimentos Financeiros (clique para expandir)</a></div>
    <div id="search-params" class="panel-body" style="display: none">
      <%= form_tag(movements_path, method: :get) do %>
      <p><b>Mostrar:</b> 
      <%= link_to "Últimos 7 dias", movements_path(:sd => 7.days.ago.strftime("%Y-%m-%d")) %>&nbsp;
      <%= link_to "Últimos 15 dias", movements_path(:sd => 15.days.ago.strftime("%Y-%m-%d")) %>&nbsp;
      <%= link_to "Últimos 30 dias", movements_path(:sd => 30.days.ago.strftime("%Y-%m-%d")) %></p>&nbsp;
      <%= link_to "Todos", movements_path(:sd => 30.years.ago.strftime("%Y-%m-%d")) %></p>
      <p>Período específico começando em <%= date_field_tag "sd", params[:sd] %> até <%= date_field_tag "ed", params[:ed] %></p>
      <p>Descrição: <%= text_field_tag "d", params[:d] %></p>
      <p>Valor: <%= text_field_tag "v", params[:v] %></p>
      <p>Exibir somente conta/caixa: <%= select_tag "b", options_from_collection_for_select(@banks, "id", "name"), prompt: "Todos" %></p>
      <p><%= submit_tag "Pesquisar" %></p>
      <% end %>
    </div>
  </div>


kamila.passos@araujo.com.br
3270-5174


<table class="table table-striped">
  <thead>
    <tr>
      <th>Data</th>
      <th>Description</th>
      <th>Valor</th>
      <th>Turma</th>
      <th>Conta</th>
      <th>Centro de Resultado</th>
      <th>CC/Caixa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
        <td><%= l movement.due_date %></td>
        <td><%= movement.description %></td>
        <td style="text-align: right;"><%= number_to_currency movement.value, unit: "" %>&nbsp;<%= movement.credit ? "C" : "D" %></td>
        <td><%= movement.course_class %></td>
        <td><%= movement.account %></td>
        <td><%= movement.result_center %></td>
        <td><%= movement.bank %></td>
        <td><%= link_to 'Ver', movement %></td>
        <td><%= link_to 'Editar', edit_movement_path(movement) %></td>
        <td><%= link_to 'Apagar', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo lançamento', new_movement_path %> | <%= link_to 'Relatório para Contabilidade', accountant_movements_path %>

app/views/movements/new.html.erb
<h1>Novo movimento financeiro</h1>

<%= render 'form' %>

<%= link_to t("commands.back"), movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('simple_form.labels.movement.due_date') %>:</strong>
  <%= @movement.due_date %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.movement.description') %>:</strong>
  <%= @movement.description %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.movement.value') %>:</strong>
  <%= @movement.value %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.movement.course_class') %>:</strong>
  <%= @movement.course_class %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.movement.account') %>:</strong>
  <%= @movement.account %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.movement.result_center') %>:</strong>
  <%= @movement.result_center %>
</p>

<p>
  <strong><%= I18n.t('simple_form.labels.movement.bank') %>:</strong>
  <%= @movement.bank %>
</p>

<% if @movement.transfer then %>
  <p>
    <strong><%= I18n.t('simple_form.labels.movement.transfer') %> para:</strong>
    <%= @movement.to_bank %>
  </p>
<% end %>

<% if @movement.accountable then %>
  <p>
    Será enviado para a Contabilidade
  </p>
<% end %>

<% if @movement.document_image? then %>
  <p>
    <%= link_to("Visualizar #{I18n.t('simple_form.labels.movement.document_image')}", @movement.document_image.url, target: "_blank") if @movement.document_image? %>
  </p>
<% end %>

<% if @movement.receipt_image? then %>
  <p>
    <%= link_to("Visualizar #{I18n.t('simple_form.labels.movement.receipt_image')}", @movement.receipt_image.url, target: "_blank") if @movement.receipt_image? %>
  </p>
<% end %>

<% unless @movement.payment_document == nil %>
  <p>
    <%= link_to "Inscrição de origem", @movement.payment_document.subscription %>
  </p>
<% end %>

<% if @movement.bank.material then %>
<table class="table table-striped" id="subscription_payment_documents">
  <thead>
    <th><%= I18n.t('simple_form.labels.material.description') %></th>
    <th><%= I18n.t('simple_form.labels.material.quantity') %></th>
    <th><%= I18n.t('simple_form.labels.material.unit_value') %></th>
  </thead>
  <tbody>
    <% @movement.materials.each do |m| %>
      <td><%= m.description %></td>
      <td><%= m.quantity %></td>
      <td><%= number_to_currency m.unit_value %></td>
    <% end %>
  </tbody>
</table>
<% end %>

<%= link_to t("commands.edit"), edit_movement_path(@movement) %> |
<%= link_to t("commands.back"), movements_path %>