config/routes.rb
Rails.application.routes.draw do
  resources :materials

  get 'pages/admin'

  resources :prices

  resources :banks

  resources :movements do
    collection do
      get 'accountant'
    end
  end

  resources :accounts

  resources :result_centers

  get 'payment_documents/generate'
  get 'payment_documents/new'
  post 'payment_documents/create'
  post 'payment_documents/insert'
  get 'payment_documents/payment'
  get 'payment_documents/edit'
  post 'payment_documents/update'
  post 'payment_documents/confirm'

  resources :subscriptions

  resources :salesmen

  resources :participants

  resources :companies

  resources :course_classes do
    member do
      get 'subscriptions'
      get 'prices'
    end
  end

  resources :trainers

  resources :courses

  devise_for :users, :controllers => { :registrations => "registrations", :invitations => "invitations" }
  resources :users
  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/course_classes_controller.rb
class CourseClassesController < ApplicationController
  before_action :set_course_class, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html, :json

  def index
    @course_classes = CourseClass.index_list
    respond_with(@course_classes)
  end

  def show
    respond_with(@course_class)
  end

  def new
    @course_class = CourseClass.new
    respond_with(@course_class)
  end

  def edit
  end

  def create
    @course_class = CourseClass.new(course_class_params)
    @course_class.save
    respond_with(@course_class)
  end

  def update
    @course_class.update(course_class_params)
    respond_with(@course_class)
  end

  def destroy
    @course_class.destroy
    respond_with(@course_class)
  end

  def prices
    #@prices = Course.joins(:course_classes).where("course_classes.id = ?", params[:id]).first.get_price_list
    cc = CourseClass.find params[:id]
    @prices = cc.course.active_prices
    respond_with(@prices)
  end

  # def dates
  #   @calendar = CourseClassDate.get_dates_from_list(params[:dates])
  #   render json: @calendar
  # end

  def subscriptions
    @subscriptions = Subscription.where(course_class_id: params[:id])
    respond_with(@subscriptions)
  end

  private
    def set_course_class
      @course_class = CourseClass.find(params[:id])
    end

    def course_class_params
      params.require(:course_class).permit(:course_id, :result_center_id, :city, :address, :start_time, :end_time, :date_list, :identifier, {:trainer_ids => []})
    end
end

app/helpers/course_classes_helper.rb
module CourseClassesHelper
end

app/views/course_classes/_form.html.erb
<%= simple_form_for(@course_class) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :course %>
    <%= f.association :trainers, as: :check_boxes, label_method: :name, value_method: :id, label: 'Trainers' %>
    <%= f.association :result_center %>
    <%= f.input :city %>
    <%= f.input :address %>
    <%= f.input :identifier %>
    <%= f.input :date_list, input_html: { value: @course_class.date_list_edit } %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/course_classes/calendar.html.erb
<table class="table table-bordered">
    <tr>
        <th>D</th>
        <th>S</th>
        <th>T</th>
        <th>Q</th>
        <th>Q</th>
        <th>S</th>
        <th>S</th>
    </tr>
    <% @calendar.each do |w| %>
    <tr>
        <% w.each do |d| %>
        <td><%= check_box "course_class", "dates", {}, d unless d == nil %>
            <%= "#{d.day}/#{d.month}" unless d == nil %></td>
        <% end %> 
    </tr>
    <% end %>
</table>

app/views/course_classes/edit.html.erb
<h1>Editing course_class</h1>

<%= render 'form' %>

<%= link_to t("commands.show"), @course_class %> |
<%= link_to t("commands.back"), course_classes_path %>

app/views/course_classes/index.html.erb
<h1>Listing course_classes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Código</th>
      <th>Treinamento</th>
      <th>Cidade</th>
      <th>Início</th>
      <th>Trainers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_classes.each do |course_class| %>
      <tr>
        <td><%= course_class.identifier %></td>
        <td><%= course_class.course %></td>
        <td><%= course_class.city %></td>
        <td><%= course_class.begin_date %></td>
        <td><%= course_class.trainer_names %></td>
        <td><%= link_to t("commands.show"), course_class %></td>
        <td><%= link_to t("commands.edit"), edit_course_class_path(course_class) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course class', new_course_class_path %>

app/views/course_classes/new.html.erb
<h1>New course_class</h1>

<%= render 'form' %>

<%= link_to t("commands.back"), course_classes_path %>

app/views/course_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código da turma:</strong>
  <%= @course_class.identifier %>
</p>

<p>
  <strong>Programa:</strong>
  <%= @course_class.course %>
</p>

<p>
  <strong>Trainers:</strong>
  <%= @course_class.trainer_names %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @course_class.city %>
</p>

<p>
  <strong>Local das Sessões:</strong>
  <%= @course_class.address %>
</p>

<p>
  <strong>Datas das Sessões:</strong>
  <%= @course_class.class_dates %>
</p>

<p>
  <strong>Horário:</strong>
  <%= @course_class.class_times %>
</p>

<p>
  <strong>Participantes:</strong>
</p>
<table class="table table-striped">
  <thead>
    <th>Nome</th>
    <th>Telefone</th>
    <th>Celular</th>
    <th>E-mail</th>
    <th>
  </thead>
  <tbody>
    <% @course_class.subscriptions.includes(:participant).order("participants.name").each do |s| %>
    <tr>
      <td><%= s.participant.name %></td>
      <td><%= s.participant.phone %></td>
      <td><%= s.participant.cellphone %></td>
      <td><%= s.participant.email %></td>
      <td><%= link_to 'Ver', s %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t("commands.edit"), edit_course_class_path(@course_class) %> |
<%= link_to t("commands.back"), course_classes_path %>

app/views/course_classes/subscriptions.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th><%= I18n.t 'simple_form.labels.participant.name' %></th>
			<th><%= I18n.t 'simple_form.labels.participant.birthday' %></th>
			<th><%= I18n.t 'simple_form.labels.subscription.salesman' %></th>
			<th><%= I18n.t 'simple_form.labels.participant.address' %></th>
			<th><%= I18n.t 'simple_form.labels.participant.city' %></th>
			<th><%= I18n.t 'simple_form.labels.participant.postal_code' %></th>
			<th><%= I18n.t 'simple_form.labels.participant.phone' %></th>
			<th><%= I18n.t 'simple_form.labels.participant.cellphone' %></th>
			<th><%= I18n.t 'simple_form.labels.participant.email' %></th>
			<th><%= I18n.t 'simple_form.labels.participant.cpf' %></th>

			<th><%= I18n.t 'simple_form.labels.company.name' %></th>
			<th><%= I18n.t 'simple_form.labels.company.address' %></th>
			<th><%= I18n.t 'simple_form.labels.company.city' %></th>
			<th><%= I18n.t 'simple_form.labels.company.postal_code' %></th>
			<th><%= I18n.t 'simple_form.labels.company.phone' %></th>
			<th><%= I18n.t 'simple_form.labels.company.cnpj' %></th>
			<th><%= I18n.t 'simple_form.labels.company.responsible_name' %></th>
			<th><%= I18n.t 'simple_form.labels.company.responsible_email' %></th>
			<th><%= I18n.t 'simple_form.labels.company.responsible_job_description' %></th>

			<th><%= I18n.t 'simple_form.labels.subscription.amount' %></th>
			<th><%= I18n.t 'simple_form.labels.subscription.charge_company' %></th>
			<th><%= I18n.t 'simple_form.labels.subscription.payment_method' %></th>
			<th><%= I18n.t 'simple_form.labels.subscription.first_payment_date' %></th>
			<th><%= I18n.t 'simple_form.labels.subscription.observations' %></th>
		</tr>
	</thead>
	<tbody>
	<% @subscriptions.each do |s| %>
		<tr>
			<td><%= s.participant.name %></td>
			<td><%= s.participant.birthday %></td>
			<td><%= s.salesman %></td>
			<td><%= s.participant.address %></td>
			<td><%= s.participant.city %></td>
			<td><%= s.participant.postal_code %></td>
			<td><%= s.participant.phone %></td>
			<td><%= s.participant.cellphone %></td>
			<td><%= s.participant.email %></td>
			<td><%= s.participant.cpf %></td>

			<td><%= s.company.name %></td>
			<td><%= s.company.address %></td>
			<td><%= s.company.city %></td>
			<td><%= s.company.postal_code %></td>
			<td><%= s.company.phone %></td>
			<td><%= s.company.cnpj %></td>
			<td><%= s.company.responsible_name %></td>
			<td><%= s.company.responsible_email %></td>
			<td><%= s.company.responsible_job_description %></td>

			<td><%= s.amount %></td>
			<td><%= s.charge_company %></td>
			<td><%= s.payment_method %></td>
			<td><%= s.first_payment_date %></td>
			<td><%= s.observations %></td>
		</tr>
	<% end %>
	</tbody>
</table>