config/routes.rb
Rails.application.routes.draw do
  resources :materials

  get 'pages/admin'

  resources :prices

  resources :banks

  resources :movements do
    collection do
      get 'accountant'
    end
  end

  resources :accounts

  resources :result_centers

  get 'payment_documents/generate'
  get 'payment_documents/new'
  post 'payment_documents/create'
  post 'payment_documents/insert'
  get 'payment_documents/payment'
  get 'payment_documents/edit'
  post 'payment_documents/update'
  post 'payment_documents/confirm'

  resources :subscriptions

  resources :salesmen

  resources :participants

  resources :companies

  resources :course_classes do
    member do
      get 'subscriptions'
      get 'prices'
    end
  end

  resources :trainers

  resources :courses

  devise_for :users, :controllers => { :registrations => "registrations", :invitations => "invitations" }
  resources :users
  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  include ApplicationHelper

  has_many :subscriptions
  accepts_nested_attributes_for :subscriptions

  validates_presence_of :name, :cellphone, :email, :birthday, :marital_state, message: "Campo obrigatório para o recebimento da inscrição."
  validate :check_number_lengths

  def to_s
    self.name
  end

  def document
    self.cpf
  end

  def valid_for_charging
    err = []
    err << [:cpf, "O CPF do participante deve ser informado."] if cpf.empty? || cpf == nil
    err << [:address, "O endereço do participante deve ser informado."] if address.empty? || address == nil
    err << [:neighborhood, "O bairro do participante deve ser informado."] if neighborhood.empty? || neighborhood == nil
    err << [:city, "A cidade do participante deve ser informada."] if city.empty? || city == nil
    err << [:state, "O estado do participante deve ser informado."] if state.empty? || state == nil
    err << [:postal_code, "O CEP do participante deve ser informado."] if postal_code.empty? || postal_code == nil
    err << [:phone, "O telefone fixo do participante deve ser informado."] if phone.empty? || phone == nil
    err << [:profession, "A profissão do participante deve ser informada."] if profession.empty? || profession == nil
    err << [:job_description, "A função do participante deve ser informada."] if job_description.empty? || job_description == nil
    err
  end

  before_save do |p|
    p.phone = format_phone(p.phone)
    p.cellphone = format_phone(p.cellphone)
    p.cpf = format_cpf(p.cpf)
    p.postal_code = format_postal_code(p.postal_code)
  end

  protected

  def check_number_lengths
    errors.add(:cpf, "O CPF informado está incorreto.") unless check_number_count(cpf, 11)
    errors.add(:postal_code, "O CEP informado está incorreto.") unless check_number_count(postal_code, 8)
    errors.add(:phone, "O telefone informado está incorreto.") unless check_number_count(phone, 10, 11)
    errors.add(:cellphone, "O telefone celular informado está incorreto.") unless check_number_count(cellphone, 10, 11)
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html

  def index
    @participants = Participant.all
    respond_with(@participants)
  end

  def show
    respond_with(@participant)
  end

  def new
    @participant = Participant.new
    respond_with(@participant)
  end

  def edit
  end

  def create
    @participant = Participant.new(participant_params)
    @participant.save
    respond_with(@participant)
  end

  def update
    @participant.update(participant_params)
    respond_with(@participant)
  end

  def destroy
    @participant.destroy
    respond_with(@participant)
  end

  private
    def set_participant
      @participant = Participant.find(params[:id])
    end

    def participant_params
      params.require(:participant).permit(:name, :cpf, :birthday, :marital_state, :address, :neighborhood, :city, :state, :postal_code, :phone, :cellphone, :email, :profession, :job_description)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= simple_form_for(@participant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :cpf %>
    <%= f.input :birthday %>
    <%= f.input :marital_state %>
    <%= f.input :address %>
    <%= f.input :neighborhood %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :postal_code %>
    <%= f.input :phone %>
    <%= f.input :cellphone %>
    <%= f.input :email %>
    <%= f.input :profession %>
    <%= f.input :job_description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<p>
  <strong>Name:</strong>
  <%= participant.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= participant.cpf %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= participant.birthday %>
</p>

<p>
  <strong>Marital state:</strong>
  <%= participant.marital_state %>
</p>

<p>
  <strong>Address:</strong>
  <%= participant.address %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= participant.neighborhood %>
</p>

<p>
  <strong>City:</strong>
  <%= participant.city %>
</p>

<p>
  <strong>State:</strong>
  <%= participant.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= participant.postal_code %>
</p>

<p>
  <strong>Phone:</strong>
  <%= participant.phone %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= participant.cellphone %>
</p>

<p>
  <strong>Email:</strong>
  <%= participant.email %>
</p>

<p>
  <strong>Profession:</strong>
  <%= participant.profession %>
</p>

<p>
  <strong>Job description:</strong>
  <%= participant.job_description %>
</p>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to t("commands.show"), @participant %> |
<%= link_to t("commands.back"), participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Birthday</th>
      <th>Marital state</th>
      <th>Address</th>
      <th>Neighborhood</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Phone</th>
      <th>Cellphone</th>
      <th>Email</th>
      <th>Profession</th>
      <th>Job description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.cpf %></td>
        <td><%= participant.birthday %></td>
        <td><%= participant.marital_state %></td>
        <td><%= participant.address %></td>
        <td><%= participant.neighborhood %></td>
        <td><%= participant.city %></td>
        <td><%= participant.state %></td>
        <td><%= participant.postal_code %></td>
        <td><%= participant.phone %></td>
        <td><%= participant.cellphone %></td>
        <td><%= participant.email %></td>
        <td><%= participant.profession %></td>
        <td><%= participant.job_description %></td>
        <td><%= link_to t("commands.show"), participant %></td>
        <td><%= link_to t("commands.edit"), edit_participant_path(participant) %></td>
        <td><%= link_to t("commands.destroy"), participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to t("commands.back"), participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @participant %>

<%= link_to t("commands.edit"), edit_participant_path(@participant) %> |
<%= link_to t("commands.back"), participants_path %>