config/routes.rb
Rails.application.routes.draw do
  resources :materials

  get 'pages/admin'

  resources :prices

  resources :banks

  resources :movements do
    collection do
      get 'accountant'
    end
  end

  resources :accounts

  resources :result_centers

  get 'payment_documents/generate'
  get 'payment_documents/new'
  post 'payment_documents/create'
  post 'payment_documents/insert'
  get 'payment_documents/payment'
  get 'payment_documents/edit'
  post 'payment_documents/update'
  post 'payment_documents/confirm'

  resources :subscriptions

  resources :salesmen

  resources :participants

  resources :companies

  resources :course_classes do
    member do
      get 'subscriptions'
      get 'prices'
    end
  end

  resources :trainers

  resources :courses

  devise_for :users, :controllers => { :registrations => "registrations", :invitations => "invitations" }
  resources :users
  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :participant
  belongs_to :course_class
  belongs_to :company
  belongs_to :salesman
  belongs_to :price

  has_many :payment_documents

  accepts_nested_attributes_for :participant
  accepts_nested_attributes_for :company

  scope :payment_documents_to_be_generated, -> { includes(:company, :participant, :payment_documents).joins(:payment_documents).where(payment_documents: { generated: false }) }

  validates_presence_of :salesman, message: "Selecione o vendedor"
  validates_presence_of :course_class, message: "Selecione a turma a qual se refere essa inscrição"
  validates_presence_of :payment_method
  validates_inclusion_of :charge_company, :in => [true, false], message: "Informe para quem será feita a cobrança / emitidos os boletos"
  validates_inclusion_of :retains_iss, :in => [true, false], message: "SOMENTE PARA EMPRESAS COM SEDE EM BELO HORIZONTE: Informe se a empresa retém ISS ou não."
  validates_associated :participant, :company
  validate :check_pf_pj_info
  validate :check_first_payment_date # create

  after_validation :clear_empty_company
  before_create :fill_sequence, :fill_price

  # TODO: validador:
  # Não permitir data do primeiro pagamento após o início da turma
  # Exigir dados PF/PJ de acordo com a forma de pagamento escolhida

  after_create do |s|
    build_bank_payment_documents(s) if s.payment_method == "B"
  end

  def payer
    self.charge_company ? self.company : self.participant
  end

  def payment_method_requires_payment_document_generation?
    self.payment_method == "B"
  end

  def payment_method_requires_payment_document_input?
    self.payment_method == "C"
  end

  def has_observations?
    (!self.observations != nil && !self.observations.empty?)
  end

  def has_generated_payment_documents?
    has = false
    self.payment_documents.each do |p|
      has = has || p.generated
    end
    has
  end

  def first_training_date
    return (Date.today - 100.years) if course_class == nil || course_class.course_class_dates == nil
    course_class.course_class_dates.order("day ASC").first.day
  end

 protected

  def build_bank_payment_documents(s)
    for i in 1..s.payments_quantity 
      p = PaymentDocument.create(
        subscription: s,
        document_number: PaymentDocument.generate_billing_number(s.course_class.course.payment_identifier, s.course_class.identifier, s.salesman.identifier, s.sequence, i, payments_quantity > 9),
        value: s.price.payment_value,
        due_date: s.first_payment_date + (i - 1).month,
        generated: false,
        kind: "B")
    end
  end

  def get_next_subscription_sequence
    last_subscription = get_last_subscription
  	if last_subscription == nil then
  		1
  	else
  		last_subscription.sequence + 1
  	end
  end

  def get_last_subscription
  	Subscription.where(course_class_id: self.course_class.id).order(:sequence).last
  end

  def fill_sequence
    self.sequence = get_next_subscription_sequence
  end

  def fill_price
    price = Price.find price_id
    self.payments_quantity = price.payment_quantity
    self.amount = price.total_value
  end

  def clear_empty_company
    self.company = nil if self.company == nil || self.company.empty?
  end

  def check_pf_pj_info
    if charge_company then
      add_entity_errors(company, company.valid_for_charging)
    else
      add_entity_errors(participant, participant.valid_for_charging)
    end
  end

  def add_entity_errors(entity, err)
    err.each do |e|
      entity.errors.add(e[0], e[1])
    end
  end

  def check_first_payment_date
    errors.add(:first_payment_date, "O primeiro pagamento não pode ser posterior ao início da turma.") if new_record? && (first_payment_date > first_training_date)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html

  def index
    @subscriptions = Subscription.all
    respond_with(@subscriptions)
  end

  def show
    respond_with(@subscription)
  end

  def new
    @subscription = Subscription.new
    @subscription.participant = Participant.new
    @subscription.company = Company.new
    respond_with(@subscription)
  end

  def edit
    a = @subscription.participant.name
    if @subscription.company == nil
      @subscription.company = Company.new
    else
      a = @subscription.company.name
    end
    respond_with(@subscription)
  end

  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save && @subscription.payment_method_requires_payment_document_input?
      redirect_to(action: :new, controller: :payment_documents, :subscription_id => @subscription.id) 
    else
      respond_with(@subscription)
    end
  end

  def update
    @subscription.update(subscription_params)
    respond_with(@subscription)
  end

  def destroy
    @subscription.destroy
    respond_with(@subscription)
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def subscription_params
      params.require(:subscription).permit(:id, :participant_id, :course_class_id, :company_id, :salesman_id, :price_id, :retains_iss, :charge_company, :first_payment_date, :observations, :payment_method, company_attributes: [:name, :cnpj, :county_subscription, :address, :neighborhood, :city, :state, :postal_code, :phone, :responsible_name, :responsible_email, :responsible_job_description], participant_attributes: [:name, :cpf, :birthday, :marital_state, :address, :neighborhood, :city, :state, :postal_code, :phone, :cellphone, :email, :profession, :job_description])
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>
  <% @subscription.errors.each do |e| %>
    <%= e.to_s %>
  <% end %>

  <div class="form-inputs panel panel-primary">
    <div class="panel-heading">Dados da Venda</div>
    <div class="panel-body">
      <% if @subscription.new_record? then %>
        <%= f.association :course_class, collection: CourseClass.future, input_html: {
            dataUrl: prices_course_class_path(':course_class_id', format: :json),
            dataTarget: '#subscription_price_id'
          } %>
      <% else %>
        <%= f.label :course_class %>
        <%= f.hint @subscription.course_class.to_s %>
      <% end %>
    <% if current_user.admin? %>
      <%= f.association :salesman %>
    <% else %>
      <%= f.input :salesman_id, as: :hidden, :input_html => { :value => current_user.salesman.id } %>
    <% end %>
    </div>
  </div>
  <div class="form-inputs panel panel-primary">
    <div class="panel-heading">Dados do Participante</div>
    <div class="panel-body">
    <%= f.simple_fields_for :participant do |pf| %>
      <%= pf.input :name %>
      <%= pf.input :birthday, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12 %>
      <%= pf.input :marital_state %>
      <%= pf.input :address %>
      <%= pf.input :neighborhood %>
      <%= pf.input :phone, hint: "Telefone com DDD" %>
      <%= pf.input :cellphone, hint: "Telefone com DDD" %>
      <%= pf.input :city %>
      <%= pf.input :state, input_html: { maxlength: 2 } %>
      <%= pf.input :postal_code %>
      <%= pf.input :email %>
      <%= pf.input :cpf %>
      <%= pf.input :profession %>
      <%= pf.input :job_description %>
    <% end %>
    </div>
  </div>
  <div class="form-inputs panel panel-primary">
    <div class="panel-heading">Dados da Empresa</div>
    <div class="panel-body">
    <%= f.simple_fields_for :company do |cf| %>
      <%= cf.input :name %>
      <%= cf.input :address %>
      <%= cf.input :neighborhood %>
      <%= cf.input :phone, hint: "Telefone com DDD" %>
      <%= cf.input :postal_code %>
      <%= cf.input :city %>
      <%= cf.input :state %>
      <%= cf.input :cnpj %>
      <%= cf.input :responsible_name %>
      <%= cf.input :responsible_job_description %>
      <%= cf.input :responsible_email %>
      <%= cf.input :county_subscription %>
    <% end %>
    </div>
  </div>
  <div class="form-inputs panel panel-primary">
    <div class="panel-heading">Dados de Cobrança</div>
    <div class="panel-body">
      <!-- TODO: futuramente permitir editar forma de pagamento caso não tenha gerado documentos @subscription.has_generated_payment_documents?-->
      <p>Depois de digitados, os dados de cobrança só podem ser alterados pelo escritório.</p>
      <% unless @subscription.new_record? %>
        <%= f.label :price %>
        <%= f.hint @subscription.price.to_s %>
        <%= f.label :payment_method %>
        <%= f.hint @subscription.payment_method %>
        <%= f.label :first_payment_date %>
        <%= f.hint l(@subscription.first_payment_date) %>
        <%= f.label :charge_company %>
        <%= f.hint (@subscription.charge_company ? "Sim" : "Não") %>
        <%= f.label :retains_iss %>
        <%= f.hint (@subscription.retains_iss ? "Sim" : "Não") %>
        <% unless @subscription.observations == nil || @subscription.observations.empty? %>
        <%= f.label :observations %>
        <%= f.hint @subscription.observations %>
        <% end %>
      <% else %>
        <a name="conditions"></a>
        <%= f.input :price_id, as: :select, collection: ["Escolha a turma"], include_blank: false %> <%= link_to "Atualizar forma de pagamento", "#conditions", onclick: "$('#subscription_course_class_id').priceSelectable();$('#subscription_course_class_id').trigger('change');$('#link_update').delete();", id: "link_update" %>
        <%= f.input :payment_method, collection: [["Boleto bancário", "B"], ["Depósito em conta corrente", "D"], ["Cheques", "C"]] %>
        <%= f.input :first_payment_date, as: :date, start_year: Date.today.year, end_year: Date.today.year + 1 %>
        <%= f.input :charge_company, as: :radio_buttons %>
        <%= f.input :retains_iss, as: :radio_buttons %>
        <%= f.input :observations %>
      <% end %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/_salesmen.html.erb
<% if current_user.admin? %>
	<%= f.association :salesman %>
<% else %>
  <%= f.hidden :salesmen, current_user.salesmen.id %>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to t("commands.show"), @subscription %> |
<%= link_to t("commands.back"), subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Participant</th>
      <th>Course class</th>
      <th>Company</th>
      <th>Salesman</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.participant %></td>
        <td><%= subscription.course_class %></td>
        <td><%= subscription.company %></td>
        <td><%= subscription.salesman %></td>
        <td><%= subscription.amount %></td>
        <td><%= link_to t("commands.show"), subscription %></td>
        <td><%= link_to t("commands.edit"), edit_subscription_path(subscription) %></td>
        <td><%= link_to t("commands.destroy"), subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>Nova Inscrição</h1>

<%= render 'form' %>

<%= link_to t("commands.back"), subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Participant:</strong>
  <%= render @subscription.participant %>
</p>

<p>
  <strong>Company:</strong>
  <%= render @subscription.company unless @subscription.company == nil %>
</p>

<p>
  <strong>Course class:</strong>
  <%= @subscription.course_class %>
</p>

<p>
  <strong>Company:</strong>
  <%= @subscription.company %>
</p>

<p>
  <strong>Salesman:</strong>
  <%= @subscription.salesman %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @subscription.amount %>
</p>

<p>
  <strong>Payments:</strong>
</p>

<table class="table table-striped" id="subscription_payment_documents">
  <thead>
    <% if @subscription.payment_method_requires_payment_document_input? %>
    <th>Banco</th>
    <th>Agência</th>
    <th>Conta</th>
    <th>Nome do Emitente</th>
    <% end %>
    <th>Número do Documento</th>
    <th>Vencimento</th>
    <th>Valor</th>
    <th>Arquivo</th>
    <th>Pago?</th>
    <th><%= (@subscription.payment_method_requires_payment_document_input? ? "Depositado no" : "Gerado no" ) + " banco" %> </th>
  </thead>
  <tbody>
    <% @subscription.payment_documents.each do |p| %>
      <tr>
        <% if @subscription.payment_method_requires_payment_document_input? %>
        <td><%= p.origin_bank %></td>
        <td><%= p.agency %></td>
        <td><%= p.account %></td>
        <td><%= p.emittent %></td>
        <% end %>
        <td><%= p.document_number %></td>
        <td><%= l(p.due_date) %></td>
        <td style="text-align: right;"><%= number_to_currency p.value %></td>
        <td><%= link_to("Visualizar", p.doc_file.url, target: "_blank") if p.doc_file? %></td>
        <td><%= p.paid_date == nil ? "Não" : raw("#{p.paid_date} #{link_to(image_tag("zoom.png"), p.movement)}") %></td>
        <td><%= p.bank %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo lançamento', new_subscription_path %> |
<%= link_to 'Lista de lançamentos', subscriptions_path %> |
<%= link_to 'Corrigir este lançamento', edit_subscription_path(@subscription) %> |
<% if @subscription.payment_method_requires_payment_document_generation? %>
Editar forma de pagamento
<% end %>